### ISSUE TITLE
Does not handle expired IAM instance credentials

### ISSUE THREAD

**Issue by aspender** [hivemq/s3-cluster-discovery-plugin#1]
When running with this plugin on AWS and configured for `credentials-type:default` we expect our IAM instance profile to be used to access S3. However, after a period of time the HiveMQ log starts outputting the following error:

`2016-07-04 12:06:40,372 267030666 [cluster-executor-1935,YiWHC] ERROR cj.a - Not able to update cluster nodes via plugin system: The provided token has expired. (Service: Amazon S3; Status Code: 400; Error Code: ExpiredToken; Request ID: 297FBDE92203F27B)`

According to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html 

`These security credentials are temporary and we rotate them automatically. We make new credentials available at least five minutes prior to the expiration of the old credentials.`

The S3 cluster discovery plugin is using a cached set of credentials and does not utilise the refresh logic within the `InstanceProfileCredentialsProvider`

**Comment by aspender** [comment]
PR for this issue: https://github.com/hivemq/s3-cluster-discovery-plugin/pull/2

**Comment by schaebo** [comment]
Thank you for the improvement.

Merged the pull request.
