### ISSUE TITLE
HiveMQ 3.2.0 support

### ISSUE THREAD

**Issue by rutvijc** [hivemq/s3-cluster-discovery-plugin#3]
The HiveMQ 3.2 upgrade guide recommends upgrading plugins to work with v3.2 as below:

http://www.hivemq.com/docs/upgrade/#hivemqdocs_3_1_to_3_2_migration_guide

Does this plugin work out of the box with HiveMQ 3.2?

**Comment by dobermai** [comment]
Hi @rutvijc,

this plugin works out-of-the-box with HiveMQ 3.2.0. It doesn't use any of the new APIs introduced with HiveMQ 3.2, so the slightly older SPI version is no problem (HiveMQ is of course backwards compatible to old APIs).
