### ISSUE TITLE
S3 file prefix can't be set outside of the configuration file

### ISSUE THREAD

**Issue by tomheinan** [hivemq/s3-cluster-discovery-plugin#5]
I've been playing around with a set of ECS-based HiveMQ clusters, and I've found that this plugin is almost exactly what I need, with the exception that I can't currently use the same container image for multiple different clusters (e.g. a production cluster and a development cluster) because the S3 prefix is fixed in the `s3discovery.properties` file, which is baked into the image.

I'd like to be able to set the prefix via environment variable so that I can use the same image everywhere and just update my ECS task definitions per environment/cluster. I've made the change locally and built myself a new jar file, but I've also put in a [pull request](https://github.com/hivemq/s3-cluster-discovery-plugin/pull/4) in case you are interested in incorporating that functionality.

I've called the variable `S3_FILE_PREFIX`, but happy to change it to whatever if this is something you'd want to merge in.

**Comment by dobermai** [comment]
Thanks for the pull request! I just merged it. :)
